### ISSUE TITLE
Error trying to retrieve summoner data

### ISSUE THREAD

**Issue by marcuxyz** [NitashEU/zed.gg#1]
My Code:
```typescript
import { Queue, Region, Season } from 'zed.gg/enums';
import { RateLimit, ZedGG } from 'zed.gg';

import { CustomResponseException } from 'zed.gg/models';
import { MatchlistByAccountIdOptions } from 'zed.gg/request-options';

// ZedGG with two rate limits. 100 calls in 10 secnds and 6000 calls in 600 seconds.
let zedGG = new ZedGG(Region.BRAZIL, 'myApi', new RateLimit(10, 100)); 

zedGG.summoners.by.name('SummonerName').then(r => console.log(r));
```
Error:

```node
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(4,25): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(5,23): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(6,25): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(7,25): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(8,21): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(9,34): error TS2304: Cannot find name 'Map'.
node_modules/zed.gg/dist/models/matches/participant-timeline.model.d.ts(10,30): error TS2304: Cannot find name 'Map'.
```

**Comment by NitashEU** [comment]
Hey mate,

thank you for your participation!

You need to enable the ES6 libraries in your `tsconfig.json` file like this:

```javascript
{
    "compilerOptions": {
        "target": "es5",
        "outDir": "dist",
        "rootDir": "src",
        "sourceMap": true,
        "lib": ["es5", "es6"] // Here we say we want to include the es5 and the es6 libraries
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

Thanks to you I found another bug. I will publish the fix ASAP!

**Comment by marcuxyz** [comment]
I thank you for your participation with the community in creating something so lavish.

I would like to help create the code, I see there are some bugs, but I am suffering with a problem, my typescript is not looking into the root directory, so it ignores the tsconfig.json settings.

After the conversion, it still generated some errors that I'll post here.


```node
C:\Users\marcusmann\Projects\rio-api-nodejs\node_modules\zed.gg\enums.js:1
(function (exports, require, module, __filename, __dirname) { export * from './dist/enums';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\marcusmann\Projetcs\rio-api-nodejs\dist\app.js:3:15)

```

**Comment by NitashEU** [comment]
Hi friend, 

I will write a guide for contributing as soon as I find the time.

This is the other error I found while trying to observe your problem. Look at this issue #3 

I will try to push a fix as soon as I get home in a few hours.

**Comment by NitashEU** [comment]
I just fixed the remaining bugs. Make sure to update the npm package to the version `1.1.2`.
